# Generated by Django 5.2.8 on 2025-11-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_bio_remove_userprofile_created_at_and_more'),
    ]

    operations = [
    ]
