# Generated by Django 5.2.6 on 2025-11-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20251119_0447'),
    ]

    operations = [
    ]
