# Generated by Django 5.2.6 on 2025-11-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20251119_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
