# Generated by Django 5.2.8 on 2025-12-26 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_bio_userprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload your culinary certificate (PDF or image) - required for verification', null=True, upload_to='chefs/certificates/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('sfax', 'Sfax'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('bizerte', 'Bizerte'), ('nabeul', 'Nabeul'), ('other', 'Other Region')], max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speciality',
            field=models.CharField(blank=True, choices=[('traditional', 'Traditional Tunisian'), ('seafood', 'Seafood Specialist'), ('pastry', 'Pastry & Desserts'), ('grill', 'Grill & BBQ'), ('vegetarian', 'Vegetarian & Healthy'), ('fusion', 'Modern Fusion'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(help_text='In minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved recipes are visible to the public'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='In minutes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about your culinary journey', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='chefs/profiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('chef', 'Chef'), ('nutritionist', 'Nutritionist')], default='visitor', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
