# Generated by Django 5.2.8 on 2025-12-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_certificate_userprofile_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
