# Generated by Django 5.2.8 on 2025-12-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_recipe_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Only approved recipes are visible to the public'),
        ),
    ]
