# Generated by Django 6.0 on 2025-12-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_recipe_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved recipes are visible to the public'),
        ),
    ]
