# Generated by Django 6.0 on 2025-12-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_comment_favorite_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients (one per line)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, help_text='Preparation steps (one per line)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
