# Generated by Django 6.0 on 2026-01-04 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(help_text='Total calories per serving')),
                ('proteins', models.DecimalField(decimal_places=1, help_text='Proteins in grams', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=1, help_text='Carbohydrates in grams', max_digits=5)),
                ('fats', models.DecimalField(decimal_places=1, help_text='Fats in grams', max_digits=5)),
                ('health_rating', models.PositiveIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')])),
                ('comment', models.TextField(blank=True, help_text="Nutritionist's comment or advice")),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='accounts.recipe')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
