# Generated by Django 6.0 on 2026-01-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_recipeanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeanalysis',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Total calories per serving', null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Carbohydrates in grams', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fats in grams', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='health_rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Proteins in grams', max_digits=5, null=True),
        ),
    ]
