# Generated by Django 6.0 on 2026-01-04 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_recipeanalysis_calories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFactSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('proteins', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sugars', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('saturated_fats', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('salt', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Fact Sheet',
                'verbose_name_plural': 'Nutrition Fact Sheets',
                'ordering': ['-created_at'],
            },
        ),
    ]
