# Generated by Django 6.0 on 2026-01-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_nutritionfactsheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeanalysis',
            name='health_rating',
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
