# Generated by Django 6.0 on 2026-01-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_nutritionmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nutrition_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nutritionmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_nutrition_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
