# Generated by Django 6.0 on 2026-01-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_nutritionmessage_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionmessage',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionmessage',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
