# Generated by Django 6.0 on 2026-01-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_nutritionmessage_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeanalysis',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'Analyse Nutritionnelle', 'verbose_name_plural': 'Analyses Nutritionnelles'},
        ),
        migrations.AddField(
            model_name='recipeanalysis',
            name='health_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ⭐ Très mauvais'), (2, '2 ⭐⭐ Mauvais'), (3, '3 ⭐⭐⭐ Moyen'), (4, '4 ⭐⭐⭐⭐ Bon'), (5, '5 ⭐⭐⭐⭐⭐ Excellent')], help_text='Évaluation globale de la santé de la recette (1 à 5 étoiles)', null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='comment',
            field=models.TextField(blank=True, help_text='Commentaire du nutritionniste (facultatif)'),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipeanalysis',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
